font_family CaskaydiaMono Nerd Font Mono
bold_italic_font auto
font_size        13.0

window_padding_width 14
window_padding_height 14
hide_window_decorations titlebar-only
show_window_resize_notification no
confirm_os_window_close 0
macos_option_as_alt yes

map ctrl+insert copy_to_clipboard
map shift+insert paste_from_clipboard

single_instance yes
allow_remote_control yes

cursor_shape block
enable_audio_bell no

tab_bar_edge                bottom
tab_bar_style               powerline
tab_powerline_style         slanted
tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

foreground             #bdbdbd
background             #080808
cursor                 #9e9e9e
selection_foreground   #080808
selection_background   #b2ceee

color0  #323437
color1  #ff5454
color2  #8cc85f
color3  #e3c78a
color4  #80a0ff
color5  #cf87e8
color6  #79dac8
color7  #c6c6c6

color8  #949494
color9  #ff5189
color10 #36c692
color11 #c6c684
color12 #74b2ff
color13 #ae81ff
color14 #85dc85
color15 #e4e4e4
